#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Guillaume Coquoz

# Short bio or description (displayed in the header)
description: Interaction Design
description--short: IxD

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: 

# Site's navigation
nav:
  - title: Bread & Butter
    url: /bread-and-butter
    landing: /wonderalp
  - title: Urturn
    url: /urturn
    landing: /editor
  - title: écal
    url: /ecal
    landing: /yellow-duck

# Categories' navigation
bread-and-butter-nav: 
  - title: Wonderalp
    url: /bread-and-butter/wonderalp
  - title: Omega
    url: /bread-and-butter/omega
  - title: The 210
    url: /bread-and-butter/the-210
  - title: Pictet
    url: /bread-and-butter/pictet
  - title: Andjoy
    url: /bread-and-butter/andjoy
urturn-nav: 
  - title: Editor
    url: /urturn/editor
  - title: Player
    url: /urturn/player
  - title: Factory
    url: /urturn/factory
  - title: Icons
    url: /urturn/icons
ecal-nav: 
  - title: Yellow Duck
    url: /ecal/yellow-duck
  - title: Abyss
    url: /ecal/abyss
  - title: Thump The Table
    url: /ecal/thump-the-table
  - title: Boombox
    url: /ecal/boombox
#
# Flags below are optional
#

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: guillaumecoquoz.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Your site's Github repository URL
github_url: "https://github.com/guillaumecoquoz/guillaumecoquoz.github.io"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag # https://help.github.com/articles/search-engine-optimization-for-github-pages/
  - jemoji # https://help.github.com/articles/emoji-on-github-pages/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# To be able to access the server with other devices (uncomment "host:…")
# Simply go to <server-device-IP-adress>:4000 on any device browser
# !this allow anyone on the network to access the server because it binds server to all available IPs!
# host: 0.0.0.0